- name: Deploy Dockerized Nginx App
  hosts: web
  become: yes

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Python Docker SDK
      apt:
        name: python3-docker
        state: present

    - name: Remove old container if exists
      community.docker.docker_container:
        name: mycontainer
        state: absent
        force_kill: yes
      ignore_errors: yes

    - name: Remove old image if exists
      community.docker.docker_image:
        name: myapp
        state: absent
      ignore_errors: yes

    - name: Build Docker image
      community.docker.docker_image:
        name: myapp
        source: build
        force_source: yes
        build:
          path: /home/ubuntu/devops-cloud-automation/app
        state: present

    - name: Run Docker container
      community.docker.docker_container:
        name: mycontainer
        image: myapp
        state: started
        recreate: yes
        restart_policy: always
        ports:
          - "80:80"
