name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Install Docker Collection
        run: |
          ansible-galaxy collection install community.docker

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > anu-key.pem
          chmod 400 anu-key.pem

      - name: Disable Host Key Checking
        run: |
          echo "ANSIBLE_HOST_KEY_CHECKING=False" >> $GITHUB_ENV

      - name: Pull Latest Code on EC2
        run: |
          ssh -i anu-key.pem -o StrictHostKeyChecking=no ubuntu@54.247.226.78 "cd devops-cloud-automation && git pull"

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory ansible/nginx-playbook.yml
